name: Deploy lib

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: create .npmrc file
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
    - name: Install dependencies
      run: npm install
    - name: Run lint
      run: npm run lint
    - name: Run tests
      run: npm run test:cov
    - name: Run build
      run: npm run build
    - name: publish to npm
      run: cd dist && npm publish